In [45]:
from tensorflow.keras.preprocessing.text import one_hot


In [47]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [48]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [49]:
## Define the vocabulary size
voc_size=10000

In [50]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [51]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3725, 5492, 7108, 4192],
 [3725, 5492, 7108, 9875],
 [3725, 9308, 7108, 6349],
 [5676, 4002, 9360, 4128, 911],
 [5676, 4002, 9360, 4128, 4349],
 [7992, 3725, 278, 7108, 5955],
 [5154, 7319, 9357, 4128]]

In [53]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
 

In [54]:
import numpy as np

In [55]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3725 5492 7108 4192]
 [   0    0    0    0 3725 5492 7108 9875]
 [   0    0    0    0 3725 9308 7108 6349]
 [   0    0    0 5676 4002 9360 4128  911]
 [   0    0    0 5676 4002 9360 4128 4349]
 [   0    0    0 7992 3725  278 7108 5955]
 [   0    0    0    0 5154 7319 9357 4128]]


In [56]:
## feature representation
dim=10


In [57]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [61]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [62]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[-3.94062027e-02, -2.66842730e-02, -2.41497885e-02,
         -3.36559303e-02, -2.49200705e-02, -1.69506781e-02,
          4.17963378e-02, -2.80027632e-02,  3.13694142e-02,
          3.03179510e-02],
        [-3.94062027e-02, -2.66842730e-02, -2.41497885e-02,
         -3.36559303e-02, -2.49200705e-02, -1.69506781e-02,
          4.17963378e-02, -2.80027632e-02,  3.13694142e-02,
          3.03179510e-02],
        [-3.94062027e-02, -2.66842730e-02, -2.41497885e-02,
         -3.36559303e-02, -2.49200705e-02, -1.69506781e-02,
          4.17963378e-02, -2.80027632e-02,  3.13694142e-02,
          3.03179510e-02],
        [-3.94062027e-02, -2.66842730e-02, -2.41497885e-02,
         -3.36559303e-02, -2.49200705e-02, -1.69506781e-02,
          4.17963378e-02, -2.80027632e-02,  3.13694142e-02,
          3.03179510e-02],
        [ 3.98455895e-02,  2.18478329e-02, -4.06123027e-02,
         -2.79266592e-02,  3.05422209e-02, -4.79837321e-02,
         -9.43031162e-03, -4.94796149e-02,  3.882249

In [63]:
embedded_docs[0]

array([   0,    0,    0,    0, 3725, 5492, 7108, 4192], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])